In [25]:
import numpy as np
import pandas as pd

In [26]:
#There is a blank line as first row in csv file
football_df= pd.read_csv("Laliga.csv", skip_blank_lines=True,skiprows=1)#skip rows

In [27]:
football_df.head().T

,0,1,2,3,4
Pos,1,2,3,4,5
Team,Real Madrid,Barcelona,Atletico Madrid,Valencia,Athletic Bilbao
Seasons,86,86,80,82,86
Points,4385,4262,3442,3386,3368
GamesPlayed,2762,2762,2614,2664,2762
GamesWon,1647,1581,1241,1187,1209
GamesDrawn,552,573,598,616,633
GamesLost,563,608,775,861,920
GoalsFor,5947,5900,4534,4398,4631
GoalsAgainst,3140,3114,3309,3469,3700
Champion,33,25,10,6,8
Runner-up,23,25,8,6,7
Third,8,12,16,10,10
Fourth,8,12,9,11,5
Fifth,3,4,7,10,8
Sixth,4,6,6,7,10
T,79,83,56,50,49
Debut,1929,1929,1929,1931-32,1929
Since/LastApp,1929,1929,2002-03,1987-88,1929
BestPosition,1,1,1,1,1

In [28]:
football_df.tail().T

                    56       57               58                59       60
Pos                 57       58               59                60       61
Team             Xerez   Condal  Atletico Tetuan  Cultural Leonesa   Girona
Seasons              1        1                1                 1        1
Points              34       22               19                14        -
GamesPlayed         38       30               30                30        -
GamesWon             8        7                7                 5        -
GamesDrawn          10        8                5                 4        -
GamesLost           20       15               18                21        -
GoalsFor            38       37               51                34        -
GoalsAgainst        66       57               85                65        -
Champion             -        -                -                 -        -
Runner-up            -        -                -                 -        -
Third                -        -                -                 -        -
Fourth               -        -                -                 -        -
Fifth                -        -                -                 -        -
Sixth                -        -                -                 -        -
T                    -        -                -                 -        -
Debut          2009-10  1956-57          1951-52           1955-56  2017-18
Since/LastApp  2009-10  1956-57          1951-52           1955-56  2017-18
BestPosition        20       16               16                15        9

In [29]:
football_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 20 columns):
Pos              61 non-null int64
Team             61 non-null object
Seasons          61 non-null int64
Points           61 non-null object
GamesPlayed      61 non-null object
GamesWon         61 non-null object
GamesDrawn       61 non-null object
GamesLost        61 non-null object
GoalsFor         61 non-null object
GoalsAgainst     61 non-null object
Champion         61 non-null object
Runner-up        61 non-null object
Third            61 non-null object
Fourth           61 non-null object
Fifth            61 non-null object
Sixth            61 non-null object
T                61 non-null object
Debut            61 non-null object
Since/LastApp    61 non-null object
BestPosition     61 non-null int64
dtypes: int64(3), object(17)
memory usage: 9.6+ KB

In [30]:
#Q1 Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)
# We are replacing with string 0 as we are going to invoke to_numeric in next steps
football_df.replace(to_replace='-', value='0', inplace=True)
#We will perform to numeric on columns other than the columns which are either already numeric or which are of the type which
#doesnt need to be converted to numeric
cols = football_df.columns.drop(["Pos", "Team", "Seasons", "Debut", "Since/LastApp","BestPosition"])
football_df[cols] = football_df[cols].apply(pd.to_numeric, errors='coerce')
football_df.dtypes

Pos               int64
Team             object
Seasons           int64
Points            int64
GamesPlayed       int64
GamesWon          int64
GamesDrawn        int64
GamesLost         int64
GoalsFor          int64
GoalsAgainst      int64
Champion          int64
Runner-up         int64
Third             int64
Fourth            int64
Fifth             int64
Sixth             int64
T                 int64
Debut            object
Since/LastApp    object
BestPosition      int64
dtype: object

In [31]:
football_df.tail().T

                    56       57               58                59       60
Pos                 57       58               59                60       61
Team             Xerez   Condal  Atletico Tetuan  Cultural Leonesa   Girona
Seasons              1        1                1                 1        1
Points              34       22               19                14        0
GamesPlayed         38       30               30                30        0
GamesWon             8        7                7                 5        0
GamesDrawn          10        8                5                 4        0
GamesLost           20       15               18                21        0
GoalsFor            38       37               51                34        0
GoalsAgainst        66       57               85                65        0
Champion             0        0                0                 0        0
Runner-up            0        0                0                 0        0
Third                0        0                0                 0        0
Fourth               0        0                0                 0        0
Fifth                0        0                0                 0        0
Sixth                0        0                0                 0        0
T                    0        0                0                 0        0
Debut          2009-10  1956-57          1951-52           1955-56  2017-18
Since/LastApp  2009-10  1956-57          1951-52           1955-56  2017-18
BestPosition        20       16               16                15        9

In [32]:
#Q2Print all the teams which have started playing between 1930-1980. (5 points)
#Q2Step1 - Since debut is a string with hyphen so we cannot do operations on it so split the debut into two 
# columns start and end
football_df[['DebutStart','DebutEnd']] = football_df['Debut'].str.split('-', expand=True)
#prepend first two characters of year like 19 or 20 to debut end in all dates except where debut end is None
football_df.loc[(football_df['DebutEnd'].isnull() == False),['DebutEnd']] = football_df['DebutStart'].str[:2]+football_df['DebutEnd'].astype(str)
football_df[['DebutStart','DebutEnd']]

   DebutStart DebutEnd
0        1929     None
1        1929     None
2        1929     None
3        1931     1932
4        1929     None
5        1934     1935
6        1929     None
7        1929     None
8        1939     1940
9        1932     1933
10       1941     1942
11       1939     1940
12       1948     1949
13       1929     None
14       1944     1945
15       1935     1936
16       1949     1950
17       1933     1934
18       1960     1961
19       1951     1952
20       1998     1999
21       1941     1942
22       1977     1978
23       1959     1960
24       2004     2005
25       1935     1936
26       1961     1962
27       1940     1941
28       1930     1931
29       1963     1964
..        ...      ...
31       1943     1944
32       1977     1978
33       1987     1988
34       1941     1942
35       1991     1992
36       2007     2008
37       1962     1963
38       1994     1995
39       1978     1979
40       1971     1972
41       1963     1964
42       1999     1900
43       2014     2015
44       1929     None
45       1990     1991
46       1947     1948
47       1996     1997
48       1995     1996
49       1945     1946
50       1953     1954
51       1929     None
52       1979     1980
53       1929     None
54       1950     1951
55       2016     2017
56       2009     2010
57       1956     1957
58       1951     1952
59       1955     1956
60       2017     2018

[61 rows x 2 columns]

In [37]:
#Q2 Step2 Remove the debut column as it has been split into two columns
football_df.drop("Debut", inplace=True, axis=1)
#remove None values from Debut End
football_df.loc[football_df["DebutEnd"].isnull() == True,"DebutEnd"] = '0'
football_df[['DebutStart','DebutEnd']]

   DebutStart DebutEnd
0        1929        0
1        1929        0
2        1929        0
3        1931     1932
4        1929        0
5        1934     1935
6        1929        0
7        1929        0
8        1939     1940
9        1932     1933
10       1941     1942
11       1939     1940
12       1948     1949
13       1929        0
14       1944     1945
15       1935     1936
16       1949     1950
17       1933     1934
18       1960     1961
19       1951     1952
20       1998     1999
21       1941     1942
22       1977     1978
23       1959     1960
24       2004     2005
25       1935     1936
26       1961     1962
27       1940     1941
28       1930     1931
29       1963     1964
..        ...      ...
31       1943     1944
32       1977     1978
33       1987     1988
34       1941     1942
35       1991     1992
36       2007     2008
37       1962     1963
38       1994     1995
39       1978     1979
40       1971     1972
41       1963     1964
42       1999     1900
43       2014     2015
44       1929        0
45       1990     1991
46       1947     1948
47       1996     1997
48       1995     1996
49       1945     1946
50       1953     1954
51       1929        0
52       1979     1980
53       1929        0
54       1950     1951
55       2016     2017
56       2009     2010
57       1956     1957
58       1951     1952
59       1955     1956
60       2017     2018

[61 rows x 2 columns]

In [40]:
#Q2 Step 3 convert all debut columns to numeric 
football_df["DebutStart"] = football_df["DebutStart"].apply(pd.to_numeric, errors = 'coerce')
football_df["DebutEnd"] = football_df["DebutEnd"].apply(pd.to_numeric, errors = 'coerce')

#Q2 Step 4 Get all teams with debut between 1930-1980
teams = (football_df[((football_df['DebutStart'] >= 1930) & (football_df['DebutStart'] <= 1980)) |
           ((football_df['DebutEnd'] >= 1930) & (football_df['DebutEnd'] <= 1980))][['Team','DebutStart','DebutEnd']])
print(teams)
teams.info()

                   Team  DebutStart  DebutEnd
3              Valencia        1931      1932
5               Sevilla        1934      1935
8              Zaragoza        1939      1940
9            Real Betis        1932      1933
10  Deportivo La Coruna        1941      1942
11           Celta Vigo        1939      1940
12           Valladolid        1948      1949
14       Sporting Gijon        1944      1945
15              Osasuna        1935      1936
16               Malaga        1949      1950
17               Oviedo        1933      1934
18             Mallorca        1960      1961
19           Las Palmas        1951      1952
21              Granada        1941      1942
22       Rayo Vallecano        1977      1978
23                Elche        1959      1960
25             Hercules        1935      1936
26             Tenerife        1961      1962
27               Murcia        1940      1941
28               Alaves        1930      1931
29              Levante        1963      1964
30            Salamanca        1974      1975
31             Sabadell        1943      1944
32                Cadiz        1977      1978
34            Castellon        1941      1942
37              Cordoba        1962      1963
39           Recreativo        1978      1979
40            Burgos CF        1971      1972
41           Pontevedra        1963      1964
46            Gimnastic        1947      1948
49             Alcoyano        1945      1946
50                 Jaen        1953      1954
52           AD Almeria        1979      1980
54               Lleida        1950      1951
57               Condal        1956      1957
58      Atletico Tetuan        1951      1952
59     Cultural Leonesa        1955      1956
<class 'pandas.core.frame.DataFrame'>
Int64Index: 37 entries, 3 to 59
Data columns (total 3 columns):
Team          37 non-null object
DebutStart    37 non-null int64
DebutEnd      37 non-null int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [143]:
#Q3 Print the list of teams which came Top 5 in terms of points (2.5 points)
#Laliga.csv pos column indicates position of team and Points indicates points held by each team
# pos column is already in ascending order and corresponding points are in descending order so top 5 rows represent team with 
# top 5 points
#football_df.loc[0:4, ['Pos', 'Team', 'Points']]
#To ensure that if csv changes still we get desired result we will use nlargest
(football_df.nlargest(5, 'Points'))[['Pos','Team','Points']]

   Pos             Team  Points
0    1      Real Madrid    4385
1    2        Barcelona    4262
2    3  Atletico Madrid    3442
3    4         Valencia    3386
4    5  Athletic Bilbao    3368

In [163]:
#Q4 Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences.
#Using the same function, find the team which has maximum and minimum goal difference. (5 points)
#Goal_diff_count = GoalsFor - GoalsAgainst
def Goal_diff_count():
      return football_df['GoalsFor'] - football_df['GoalsAgainst']
        
goaldiff_df = Goal_diff_count()
print("The team with maximum goal difference is\n",football_df.loc[goaldiff_df.idxmax(),["Team","GoalsFor", "GoalsAgainst"]]) 
print("The team with minimum goal difference is\n",football_df.loc[goaldiff_df.idxmin(),["Team","GoalsFor", "GoalsAgainst"]])

The team with maximum goal difference is
 Team            Real Madrid
GoalsFor               5947
GoalsAgainst           3140
Name: 0, dtype: object
The team with minimum goal difference is
 Team            Racing Santander
GoalsFor                    1843
GoalsAgainst                2368
Name: 13, dtype: object

In [149]:
#Q5
#Q5 1Create a new column with name “Winning Percent” and append it to the data set (5 points)
# Percentage of Winning = (GamesWon / GamesPlayed)*100
football_df["Winning Percent"] = (football_df["GamesWon"]/football_df["GamesPlayed"])*100

In [150]:
#Q5 2 If there are any numerical error, replace it with 0%
print("Before :\n", football_df[["Winning Percent"]])
football_df[football_df["Winning Percent"].isna()] = 0
print("After :\n",football_df[["Winning Percent"]])

Before :
     Winning Percent
0         59.630702
1         57.241130
2         47.475134
3         44.557057
4         43.772629
5         41.112957
6         36.100533
7         37.532580
8         35.146022
9         35.069444
10        36.797386
11        34.511190
12        31.582538
13        31.722689
14        32.304527
15        32.321700
16        31.075697
17        34.228188
18        33.704453
19        33.485401
20        41.176471
21        29.380054
22        28.987730
23        29.941003
24        32.236842
25        29.299363
26        31.376518
27        24.744027
28        32.894737
29        28.109453
..              ...
31        30.281690
32        23.214286
33        27.745665
34        30.838323
35        28.148148
36        27.192982
37        29.078014
38        32.500000
39        26.881720
40        28.921569
41        29.444444
42        24.342105
43        30.701754
44        33.076923
45        22.807018
46        29.310345
47        25.000000
48        23.750000
49        27.777778
50        32.222222
51        29.166667
52        25.000000
53        33.333333
54        19.117647
55        21.052632
56        21.052632
57        23.333333
58        23.333333
59        16.666667
60              NaN

[61 rows x 1 columns]
After :
     Winning Percent
0         59.630702
1         57.241130
2         47.475134
3         44.557057
4         43.772629
5         41.112957
6         36.100533
7         37.532580
8         35.146022
9         35.069444
10        36.797386
11        34.511190
12        31.582538
13        31.722689
14        32.304527
15        32.321700
16        31.075697
17        34.228188
18        33.704453
19        33.485401
20        41.176471
21        29.380054
22        28.987730
23        29.941003
24        32.236842
25        29.299363
26        31.376518
27        24.744027
28        32.894737
29        28.109453
..              ...
31        30.281690
32        23.214286
33        27.745665
34        30.838323
35        28.148148
36        27.192982
37        29.078014
38        32.500000
39        26.881720
40        28.921569
41        29.444444
42        24.342105
43        30.701754
44        33.076923
45        22.807018
46        29.310345
47        25.000000
48        23.750000
49        27.777778
50        32.222222
51        29.166667
52        25.000000
53        33.333333
54        19.117647
55        21.052632
56        21.052632
57        23.333333
58        23.333333
59        16.666667
60         0.000000

[61 rows x 1 columns]

In [19]:
#Q5 3 Print the top 5 teams which has the highest Winning percentage
(football_df.nlargest(5, "Winning Percent")).T

,0,1,2,3,4
Pos,1,2,3,4,5
Team,Real Madrid,Barcelona,Atletico Madrid,Valencia,Athletic Bilbao
Seasons,86,86,80,82,86
Points,4385,4262,3442,3386,3368
GamesPlayed,2762,2762,2614,2664,2762
GamesWon,1647,1581,1241,1187,1209
GamesDrawn,552,573,598,616,633
GamesLost,563,608,775,861,920
GoalsFor,5947,5900,4534,4398,4631
GoalsAgainst,3140,3114,3309,3469,3700
Champion,33,25,10,6,8
Runner-up,23,25,8,6,7
Third,8,12,16,10,10
Fourth,8,12,9,11,5
Fifth,3,4,7,10,8
Sixth,4,6,6,7,10
T,79,83,56,50,49
Since/LastApp,1929,1929,2002-03,1987-88,1929
BestPosition,1,1,1,1,1
Debut Start,1929,1929,1929,1931,1929
Debut End,NaN,NaN,NaN,32,NaN
Goals_diff,2807,2786,1225,929,931
Winning Percent,59.6307,57.2411,47.4751,44.5571,43.7726

In [69]:
#Q6 Group teams based on their “Best position” and print the sum of their points for all positions (5 points)
#Eg: Best Position                Points
#        1                              25000
#        2                              7000for
(football_df.groupby(["BestPosition"]))[['Points']].sum()

              Points
BestPosition
0                  0
1              27933
2               6904
3               5221
4               6563
5               1884
6               2113
7               1186
8               1134
9                 96
10               450
11               445
12               511
14                71
15                14
16                81
17               266
19                81
20                34